### ISSUE TITLE
How to switch the guest_vm in app vm_multi?

### ISSUE THREAD

**Issue by Jerryy959** [tiiuae/tii_sel4_build#7] opened 2022-04-22 15:42 UTC
Hi,
I successfully run the branch "rpi4"  to launch two guest linux on my board. But there is a small problem happened that i can't switch the **vm console** on the uart output of my rpi4.

Is there any method to get my goal ?  when use the rpi4 branch, i can't use "@N" to switch just like [camkes-vm from sel4](https://github.com/seL4/camkes-vm#Serial).

**Comment by hlyytine** [comment] 2022-04-22 20:04
We found out that often SerialServer responds to "@n" only after a newline. So try hitting the Enter key few times and then retry "@n". Repeat this a few times if it does not work on the first try.

**Comment by Jerryy959** [comment] 2022-04-28 08:50
Thanks, but i test again, and get the same result. There is not **colour coded**, and the shell (**screeen /dev/ttyUSB0 115200**) return me "command not found." when i enter the "@n". This may be caused by my wrong operation，but I don't know what went wrong. 
Can you tell me where the source code of serial port is? Or how can you switch the vm console? I'm really confused.

**Comment by elmankku** [comment] 2022-04-28 09:44
Which image your setup is based on?

The `vm_minimal` and `vm_multi` are configuring serial differently. The former uses pass-through devices and doesn't have serial multiplexer in the image, while the latter uses `SerialServer` (a component of seL4 user space) that works as a serial multiplexer. For the latter switching between different VMs is as described by @hlyytine - typically I prefix command with extra enter e.g. `<enter>@1`.

**Comment by hlyytine** [comment] 2022-04-28 09:53
> There is not **colour coded**

Also this makes me think you are running `vm_minimal` (which does not SerialServer nor multiple VMs) instead of `vm_multi`. The latter would have color coded output (provided your `screen` lets them through). So please clarify and/or make sure you are running the correct image.

And as a shameless plug, you can now access our previously private codebase, see https://github.com/tiiuae/tii_sel4_build/tree/wip/hlyytine-virtio-blk and the chapter about QEMU there. You might find it interesting.

**Comment by Jerryy959** [comment] 2022-04-28 15:37
@elmankku  When the ninja successfully worked with `make vm_multi `, i get the last output like this :
```
[486/486] Generating images/capdl-loader-image-arm-bcm2711
Here are your binaries in rpi4_vm_multi/images: 
total 52532
-rwxr-xr-x 1 build build 53792760 Apr 28 11:13 capdl-loader-image-arm-bcm2711
```
Then i copy the image to my SD card, and get the considered issue.

**Comment by Jerryy959** [comment] 2022-04-28 15:39
@hlyytine  OK, i will try checking the correct image and other things, then reply. Thanks!!!

**Comment by elmankku** [comment] 2022-05-11 11:03
Hey @Comet959 

We fixed the issue you had - we realized that there was one repository in wrong revision. Apologies for inconvenience!

**Comment by elmankku** [comment] 2022-05-30 06:58
Assuming the issue is fixed. Closing...

**Closed as completed by elmankku** 2022-05-30 06:58 UTC
